require("scripts/item-groups")
require("scripts/TiberiumOre")
require("scripts/TiberiumArmor")
require("scripts/TiberiumWall")
require("scripts/recipe")
require("scripts/technology")
require("scripts/TiberiumControlNetwork")
require("scripts/TiberiumPowerPlant")
require("scripts/entities")
require("scripts/items")
require("scripts/Tiberium Weapons")