require("scripts/item-groups")
require("scripts/TiberiumOre")
require("scripts/TiberiumWall")
require("scripts/recipe")
require("scripts/technology")
require("scripts/TiberiumControlNetwork")
require("scripts/TiberiumPowerPlant")
require("scripts/Tiberium Combat")
require("scripts/damage-type")
require("__LSlib__/LSlib")
require("scripts/recipe_autogeneration")