data:extend{
	--Science stuff
	{
		type = "item",
		name = "tiberium-data-mechanical",
		icon = tiberiumInternalName.."/graphics/icons/tiberium-data-mechanical.png",
		icon_size = 32,
		flags = {},
		localised_description = {"item-description.tiberium-data"},
		subgroup = "a-items",
		stack_size = 200
	},
	{
		type = "item",
		name = "tiberium-data-thermal",
		icon = tiberiumInternalName.."/graphics/icons/tiberium-data-thermal.png",
		icon_size = 32,
		flags = {},
		localised_description = {"item-description.tiberium-data"},
		subgroup = "a-items",
		stack_size = 200
	},
	{
		type = "item",
		name = "tiberium-data-chemical",
		icon = tiberiumInternalName.."/graphics/icons/tiberium-data-chemical.png",
		icon_size = 32,
		flags = {},
		localised_description = {"item-description.tiberium-data"},
		subgroup = "a-items",
		stack_size = 200
	},
	{
		type = "item",
		name = "tiberium-data-nuclear",
		icon = tiberiumInternalName.."/graphics/icons/tiberium-data-nuclear.png",
		icon_size = 32,
		flags = {},
		localised_description = {"item-description.tiberium-data"},
		subgroup = "a-items",
		stack_size = 200
	},
	{
		type = "item",
		name = "tiberium-data-EM",
		icon = tiberiumInternalName.."/graphics/icons/tiberium-data-EM.png",
		icon_size = 32,
		flags = {},
		localised_description = {"item-description.tiberium-data"},
		subgroup = "a-items",
		stack_size = 200
	},
	{
		type = "tool",
		name = "tiberium-science",
		icon = tiberiumInternalName.."/graphics/icons/tacitus.png",
		icon_size = 32,
		flags = {},
		subgroup = "a-items",
		durability = 1,
		durability_description_key = "description.science-pack-remaining-amount-key",
		durability_description_value = "description.science-pack-remaining-amount-value",
		stack_size = 200,
	},
	--Structures
	{
		type = "item",
		name = "tiberium-growth-accelerator",
		icon = tiberiumInternalName.."/graphics/technology/growth-accelerator.png",
		icon_size = 128,
		subgroup = "a-buildings",
		order = "d[tiberium-growth-accelerator]",
		place_result = "tiberium-growth-accelerator-node",
		stack_size = 15,
	},
	{
		type = "item",
		name = "tiberium-power-plant",
		icon = tiberiumInternalName.."/graphics/icons/td-power-plant.png",
		icon_size = 64,
		flags = {},
		subgroup = "a-buildings",
		order = "e[tiberium-power-plant]",
		place_result = "tiberium-power-plant",
		stack_size = 20
	},
	{
		type = "item",
		name = "tiberium-centrifuge",
		icon = "__base__/graphics/icons/centrifuge.png",
		icon_size = 64,
		flags = {},
		subgroup = "a-buildings",
		order = "a[tiberium-centrifuge]-1",
		place_result = "tiberium-centrifuge",
		stack_size = 20
	},
	{
		type = "item",
		name = "tiberium-centrifuge-2",
		icon = "__base__/graphics/icons/centrifuge.png",
		icon_size = 64,
		flags = {},
		subgroup = "a-buildings",
		order = "a[tiberium-centrifuge]-2",
		place_result = "tiberium-centrifuge-2",
		stack_size = 20
	},
	{
		type = "item",
		name = "tiberium-centrifuge-3",
		icon = "__base__/graphics/icons/centrifuge.png",
		icon_size = 64,
		flags = {},
		subgroup = "a-buildings",
		order = "a[tiberium-centrifuge]-3",
		place_result = "tiberium-centrifuge-3",
		stack_size = 20
	},
	{
		type = "item",
		name = "tiberium-srf-emitter",
		icon = tiberiumInternalName.."/graphics/sonic wall/node icon.png",
		icon_size = 32,
		subgroup = "a-buildings",
		order = "b[srf]",
		place_result = "tiberium-srf-connector",
		stack_size = 50
	},
	{
		type = "item",
		name = "tiberium-network-node",
		icon = "__base__/graphics/icons/electric-mining-drill.png",
		icon_mipmaps = 4,
		icon_size = 64,
		order = "h[tiberium-network-node]",
		place_result = "tiberium-network-node",
		stack_size = 50,
		subgroup = "a-buildings",
	},
	{
		type = "item",
		name = "tiberium-node-harvester",
		icon = "__base__/graphics/icons/pumpjack.png",
		icon_mipmaps = 4,
		icon_size = 64,
		order = "c[node-harvester]",
		place_result = "tiberium-node-harvester",
		stack_size = 20,
		subgroup = "a-buildings",
	},
	{
		type = "item",
		name = "tiberium-spike",
		icon = tiberiumInternalName.."/graphics/icons/tiberium-spike.png",
		icon_size = 128,
		order = "g[tiberium-spike]",
		place_result = "tiberium-spike",
		stack_size = 20,
		subgroup = "a-buildings",
	},
	{
		type = "item",
		name = "tiberium-beacon-node",
		icon = tiberiumInternalName.."/graphics/icons/beacon.png",
		icon_size = 32,
		order = "g[tiberium-beacon-node]",
		place_result = "tiberium-beacon-node",
		stack_size = 20,
		subgroup = "a-buildings",
	},
	{
		type = "item",
		name = "tiberium-aoe-node-harvester",
		icon = "__base__/graphics/icons/pumpjack.png",
		icon_mipmaps = 4,
		icon_size = 32,
		order = "c[aoe-node-harvester]",
		place_result = "tiberium-aoe-node-harvester",
		stack_size = 20,
		subgroup = "a-buildings",
	},
	{
		type = "item",
		name = "tiberium-ion-turret",
		icon = "__base__/graphics/icons/laser-turret.png",
		icon_size = 64,
		subgroup = "a-buildings",
		order = "f[tiberium-ion-turret]",
		place_result = "tiberium-ion-turret",
		stack_size = 50
	},
	--Military
	{
		type = "item-with-entity-data",
		name = "tiberium-marv",
		icon = tiberiumInternalName.."/graphics/icons/tiberium-marv.png",
		icon_size = 128,
		order = "e[personal-transport]-a[marv]",
		place_result = "tiberium-marv",
		stack_size = 1,
		subgroup = "a-items",
	},
	--Power
	{
		type = "item",
		name = "tiberium-empty-cell",
		icon = tiberiumInternalName.."/graphics/icons/empty-fuel-cell.png",
		icon_size = 64,
		flags = {},
		order = "c[tiberium-fuel-cell]-a[empty-cell]",
		subgroup = "a-intermediates",
		stack_size = 100
	},
	{
		type = "item",
		name = "tiberium-dirty-cell",
		icon = tiberiumInternalName.."/graphics/icons/dirty-fuel-cell.png",
		icon_size = 64,
		flags = {},
		order = "c[tiberium-fuel-cell]-c[dirty-cell]",
		subgroup = "a-intermediates",
		stack_size = 5
	},
	{
		type = "item",
		name = "tiberium-fuel-cell",
		icon = "__base__/graphics/icons/uranium-fuel-cell.png",
		icon_size = 64,
		flags = {},
		order = "c[tiberium-fuel-cell]-b[fuel-cell]",
		subgroup = "a-intermediates",
		fuel_category = "nuclear",
		burnt_result = "tiberium-dirty-cell",
		fuel_value = "4GJ",
		stack_size = 50
	},
	--Other
	{
		type = "item",
		name = "tiberium-growth-credit",
		icon = tiberiumInternalName.."/graphics/icons/growth-credit.png",
		icon_size = 64,
		flags = {},
		subgroup = "a-items",
		order = "a[tiberium-ore]",
		stack_size = 200,
	},
	{
		type = "item",
		name = "tiberium-ion-core",
		icon = tiberiumInternalName.."/graphics/icons/nuclear-reactor.png",
		icon_size = 32,
		flags = {},
		subgroup = "a-intermediates",
		order = "a[tiberium-ore]",
		stack_size = 200
	},
	{
		type = "item",
		name = "tiberium-ore",
		icon = tiberiumInternalName.."/graphics/icons/tiberium-ore.png",
		icon_size = 64,
		icon_mipmaps = 4,
		flags = {},
		subgroup = "raw-resource",
		order = "a[tiberium-ore]",
		stack_size = 50,
		fuel_value = "2MJ",
		fuel_category = "chemical",
		fuel_emissions_multiplier = 5,
	},
	--Dummy Items
	{
		type = "item",
		name = "tiberium-growth-credit-void",
		icon = tiberiumInternalName.."/graphics/icons/tiberium-ore.png",
		icon_size = 64,
		flags = {"hidden"},
		subgroup = "a-items",
		stack_size = 200
	},
}
